### PR TITLE
ARM64 builds

### LINKED ISSUE #16: ARM64 support
as docker image please :-)

### PR DESCRIPTION
**Pull request by kjde**
fixes #16 + general action update

17-alpine is x86 only. bullseye supports arm64

### CODE REVIEW

**Comment by micw** [comment]
Great, thank you. I have no way to verify that arm buils actually works. But the PR looks good to me.
Is there a way to build x64 with alpine and arm with debian?

**Comment by kjde** [comment]
I have added _master-alpine_ but kept bullseye as _master_ for compatibility.

**Comment by micw** [comment]
I have been in vacations. Just reviewed the PR. There is one minor change (don't delete the tag trigger). After this, I'll happily merge it.

**Comment by kjde** [comment]
Thank you for your work. It was a pleasure to contribute.

**Pull request merged**
